# Groups

- id: mistral
  type: group
  role: [mistral]
# add more tasks
  tasks: [globals, logging, hiera, hosts, firewall, connectivity_tests, dns-client, fuel_pkgs, netconfig, tools, ntp-client, reserved_ports, ssl-add-trust-chain, ssl-keys-saving]
  cross-depends:
    - name: primary-controller
    - name: controller
  parameters:
    strategy:
      type: parallel

# Tasks

- id: mistral-db
  version: 2.1.0
  type: puppet
  groups: [primary-controller]
  cross-depends:
    - name: /^(primary-)?database$/
#  condition:
#    yaql_exp: >
#      changedAny($.fuel-plugin-mistral, $.mysql, $.network_metadata.vips,
#      $.get('mysql_custom_setup_class'))
  parameters:
    puppet_manifest: puppet/manifests/db.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: mistral-keystone
  version: 2.1.0
  type: puppet
  groups: [primary-controller]
  cross-depends:
    - name: primary-keystone
      role: self
#  condition:
#    yaql_exp: >
#      changedAny($.fuel-plugin-mistral, $.network_metadata.vips, $.public_ssl,
#      $.get('use_ssl'), $.get('region', 'RegionOne'))
  parameters:
    puppet_manifest: puppet/manifests/keystone.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: mistral-repo
  version: 2.1.0
  type: puppet
  groups: [primary-controller, controller, mistral]
  cross-depends:
    - name: setup_repositories
      role: self
  parameters:
    puppet_manifest: puppet/manifests/repo.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360

- id: mistral-conf
  version: 2.1.0
  type: puppet
  groups: [primary-controller, controller, mistral]
  cross-depends:
    - name: mistral-repo
      role: self
  parameters:
    puppet_manifest: puppet/manifests/conf.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360

- id: mistral-db-sync
  version: 2.1.0
  type: puppet
  groups: [primary-controller]
  cross-depends:
    - name: mistral-db
      role: self
    - name: mistral-conf
      role: self
  parameters:
    puppet_manifest: puppet/manifests/db/sync.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360

- id: mistral-api
  version: 2.1.0
  type: puppet
  groups: [primary-controller, controller]
  cross-depends:
    - name: mistral-conf
      role: self
    - name: mistral-keystone
    - name: mistral-db
      role: primary-controller
    - name: mistral-db-sync
  parameters:
    puppet_manifest: puppet/manifests/api.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360

- id: mistral-vip
# May not work with dedicated haproxy
  version: 2.1.0
  type: puppet
  groups: [primary-controller, controller]
  cross-depends:
    - name: primary-cluster-haproxy
      role: self
    - name: mistral-api
      role: self
# add: if role is primary-controller (was in video)
    - name: cluster-haproxy
      role: self
# add: if role is controller (was in video)
  parameters:
    puppet_manifest: puppet/manifests/vip.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360

- id: mistral-dashboard
  version: 2.1.0
  type: puppet
  groups: [primary-controller, controller]
  cross-depends:
    - name: /.*horizon.*/
      role: self
  parameters:
    puppet_manifest: puppet/manifests/dashboard.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360

- id: mistral-engine
  version: 2.1.0
  type: puppet
  groups: [mistral]
  cross-depends:
    - name: mistral-conf
      role: self
  parameters:
    puppet_manifest: puppet/manifests/engine.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360

- id: mistral-executor
  version: 2.1.0
  type: puppet
  groups: [mistral]
  cross-depends:
    - name: mistral-conf
      role: self
  parameters:
    puppet_manifest: puppet/manifests/executor.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360

