- id: mistral_dashboard
  type: puppet
  role: ['primary-controller','controller']
  requires: [deploy_start]
  version: 2.0.0
  cross-depends:
    - name: /.*horizon.*/
      role: self
  parameters:
    puppet_manifest: puppet/manifests/dashboard.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 300
