attributes:
  metadata:
    group: 'other'
  db_password:
    label: 'db_password'
    value:
      generator: 'password'
    weight: 25
    type: "password"
    restrictions:
      - condition: "true"
        action: "hide"
  keystone_password:
    label: 'Keystone password'
    value:
      generator: 'password'
    weight: 25
    type: "password"
    restrictions:
      - condition: "true"
        action: "hide"
